name: Tests

on: [push]

jobs:
  test:
    name: Run Tests

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install libpq-dev
        run: sudo apt-get install -y libpq-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://test:test@localhost/test
        run: |
          bundle exec rubocop
          bundle exec rails db:prepare
          bundle exec rails test:all
